<a href="https://colab.research.google.com/github/a38384383020/python/blob/main/python1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Python物件
List[串列] Tuple(元組) Dictionary{字典} Sets{集合}

In [ ]:
#List[串列]
score=[90,70,80,88,95]
print(score[0])
print(score[1])
print(score[4])
print(score[-1])  #倒數第一個

90
70
95
95


In [ ]:
score=[90,70,80,88,95]
print(score[0:3])
print(score[:3])
print(score[3:])  #3到最後面
print(score[:])  #印出全部

[90, 70, 80]
[90, 70, 80]
[88, 95]
[90, 70, 80, 88, 95]
[70, 80]


In [ ]:
score=[90,70,80,88,95]
print(score[0:5:2])
print(score[::2])
print(score[4:0:-1])
print(score[0:4:-1])

[90, 80, 95]
[90, 80, 95]
[95, 88, 80, 70]
[]
[70]


In [ ]:
astr="abcdefghijklmnopqrstuvwxyz"
print(astr[0])
print(astr[-1])
print(astr[5:20])
print(astr[5:20:3])
print(astr[20:5:-1])
print(astr[20:5:-3])
print(astr[::-3])
#print(astr[3:15:-1])

a
z
fghijklmnopqrst
filor
utsrqponmlkjihg
uroli
zwtqnkheb


In [ ]:
my_list0=[]
print(my_list0)
my_list1=list()
print(my_list1)
my_list2=["python","javascript","c#"]
print(my_list2)
print(my_list2[0])
my_list2.append('java')    #加入java
print(my_list2)
my_list2.remove('java')    #刪除java
print(my_list2)
my_list2.insert(1,'java')   #插入java
print(my_list2)

[]
[]
['python', 'javascript', 'c#']
python
['python', 'javascript', 'c#', 'java']
['python', 'javascript', 'c#']
['python', 'java', 'javascript', 'c#']


In [ ]:
a=[1,2,3]
b=[4,5,6]
c=a+b
print(c)
d=2*a
print(d)

[1, 2, 3, 4, 5, 6]
[1, 2, 3, 1, 2, 3]


Turple(元組)

tuple(元組)可視為不可改變的串列，tuple跟list很像，但是我們不能新增、刪除或更新tuple的元素。tuple的好處有：

1.佔用較少空間

2.可當作dictionary(字典)的鍵值

3.可當作函式引數




In [1]:
a_tuple=('python', 'js', 'SQL')
print(a_tuple)
b_list=['go', 'c#', 'vb']
b_tuple=tuple(b_list)  #將List轉為Tuple
print(b_tuple)
print(b_tuple[0])

('python', 'js', 'SQL')
('go', 'c#', 'vb')
go


字典(dictionary - dict)為帶有鍵值(key)的串列(list)

dictionary與List不一樣的地方在於dict的索引值可改為"字串"



In [3]:
a_dict={0:'go',1:'c#',2:'vb'}
print(a_dict)
print(a_dict[0])
print(a_dict[1])
b_dict={'name':'tony','sex':'Male','sid':'B09090000'} #索引值自訂
print(b_dict['name'])

{0: 'go', 1: 'c#', 2: 'vb'}
go
c#
tony


Chap.4 numpy套件(numeric python)<br>
為什麼需要numpy?<br>
numpy由c撰寫，速度快python 10~1000倍以上<br>
numpy儲存結果較正確，python數字儲存不正確<br>
numpy節省記憶體儲存空間<br>
numpy的向量(矩陣計算)速度快<br>
numpy的取值方便

In [4]:
a_list=[1,2,3,4,5]
print(a_list*3)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [5]:
#numpy套件的ndarray型態,提供element-wise的操作
import numpy as np
a=np.array([1,2,3,4,5])
print(a*3)

[ 3  6  9 12 15]


In [8]:
a=np.array([1,2,3,4,5])
print(type(a))
print(a.shape) #ndaary的形狀
print(a.dtype) #資料的型態
print(a.ndim) #維度

<class 'numpy.ndarray'>
(5,)
int64
1


In [11]:
import numpy as np
z=np.zeros(6)
print(z)
z=np.zeros((2,3,4))
print(z)
print(np.arange(10))

[0. 0. 0. 0. 0. 0.]
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
[0 1 2 3 4 5 6 7 8 9]


2維資料取值

In [12]:
my_2d_array=np.array([np.arange(0,5),np.arange(5,10)])
print(my_2d_array)    #顯示全部資料
print(my_2d_array[1,:]) #取第'1'維資料
print(my_2d_array[:,1]) #取所有維度中,第'1'位置的資料
print(my_2d_array[1,1]) #取第'1'維中第'1'位置的資料

[[0 1 2 3 4]
 [5 6 7 8 9]]
[5 6 7 8 9]
[1 6]
6


In [14]:
a=np.zeros(10)
print(a)
print(a.ndim)   #一維List 1x10
b=a.reshape(2,5) #改變a的維度為2x5
print(b)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
1
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


#函式:
1.獨立的一組程式碼, 可以重複使用<br>
2.通常可以有0-多個輸入, 0-1個輸出<br>
3.函式輸入參數可以有預設值


In [ ]:
#傳統程式寫法
import math
radius=eval(input("請輸入員的半徑: "))
area=radius * radius * math.pi
print("圓的面積為: ",area)

請輸入員的半徑: 5
圓的面積為:  78.53981633974483


In [ ]:
#面積計算函示
import math
def circle_area(radius):
  area=radius * radius *math.pi
  return area

print(circle_area(10))
print(circle_area(5))

314.1592653589793
78.53981633974483


#錯誤處理
try:<br>
(需要檢測的程式碼)<br>
except:<br>
(錯誤時的處理方式)<br>
else:<br>
(如果沒有產生錯誤的處理方式)<br>
finally:<br>
(不管錯誤或執行正確，皆會進入處理方式)<br>
可以只有except沒有finally<br>
也可以有很多個except<br>
但只能有一個finally<br>

In [ ]:
a=5
b=10
if a<b:
  print(n)

NameError: ignored

In [ ]:
try:
  a=5
  b=10
  if a<b:
    print(n)
except NameError:
  print("名稱錯誤")
except ZeroDivisionError:
  print("處以零錯誤")
except:
  print("錯誤產生")
else:
  print("程式沒有錯誤")
finally:
  print("程式結束")

錯誤產生


#chap6 檔案處理
os套件:用來處理目錄與文件，以及檔案的讀寫

In [ ]:
import os
os.getcwd() #回傳目前的工作目錄

'/content'

In [ ]:
os.listdir(".") #列出目錄下所有檔案

['.config', 'sample_data']

In [ ]:
os.makedirs("test") #新增test目錄
os.listdir(".")

['.config', 'test', 'sample_data']

In [ ]:
os.rmdir("test") #移除test目錄
os.listdir(".")

['.config', 'sample_data']

#檔案處理
os套件有自己的檔案處理命令，而比較常用的是python內建的open<br>
w = 可寫(預設建立檔案) 若檔案存在則會清除舊檔案<br>
w+ = 可寫可讀(預設建立檔案) 若檔案存在則會清除舊檔案<br>
r = 可讀<br>
r+ = 可寫可讀 但寫入資料指向開頭<br>
a = 可寫不能讀 寫入資料指向尾端<br>
a+ = 可寫可讀 寫入資料指向尾端<br>
b = 轉為2進位文件<br>
ab+ = 2進位文件的讀寫 寫入資料指向尾端

In [ ]:
#新增檔案
a=open("a.txt","w")
a.write("This is line")
a.write("This is line2\n")
a.write("This is line3\n")
a.close()

In [ ]:
os.path.isfile("a.txt")

True

In [ ]:
a=open("a.txt", "r")
print(a.readlines())
a.close()

['This is lineThis is line2\n', 'This is line3\n']


In [ ]:
if os.path.isfile("a.txt"):
  a=open("a.txt", "r")
  print(a.readlines())
  a.close()
else:
  print("檔案不存在")

['This is lineThis is line2\n', 'This is line3\n']


#附加檔案

In [ ]:
a=open("a.txt", "a") #參數a會把寫入資訊附加在檔案尾巴
a.write("This is line4\n")
a.close()

In [ ]:
a=open("a.txt", "r")
print(a.readlines())
a.close()

['This is lineThis is line2\n', 'This is line3\n', 'This is line4\n']


In [ ]:
a=open("a.txt", "r+") #參數r+會把資訊附加在檔案開頭
a.write("This is line5\n")
a.close()

In [ ]:
a=open("a.txt", "r")
print(a.readlines())
a.close()

['This is line5\n', 'is is line2\n', 'This is line3\n', 'This is line4\n']
